# Conda is used mainly for development dependencies

channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.7
  - black
  - bump2version
  - flake8
  - ipython
  - isort
  - mypy
  - pip-tools
  - pytest
  - pytest-cov
  - tox
